name: Update Dependencies

on:
  schedule:
    - cron: '0 2 * * 1'  # Run weekly on Mondays at 2 AM
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Check for outdated dependencies
      run: |
        pip list --outdated --format=freeze > outdated.txt
        if [ -s outdated.txt ]; then
          echo "Found outdated dependencies:"
          cat outdated.txt
        else
          echo "All dependencies are up to date"
        fi
    
    - name: Create Pull Request for updates
      if: hashFiles('outdated.txt') != ''
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b update-dependencies-$(date +%Y%m%d)
        git add outdated.txt
        git commit -m "Update dependency check report"
        git push origin update-dependencies-$(date +%Y%m%d)
    
    - name: Upload dependency report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-report
        path: outdated.txt 